export function eligibleBaseAdvanceState(overrides = {}) {
  return {
    run_kind: "ordinary",
    run_status: "running-no-terminal",
    continuation_checkpoint: "absent",
    steering_queue: "empty",
    steering_boundary: "absent",
    steering_action: "absent",
    steering_fence: "absent",
    pr_authority: "absent",
    post_pr: "disabled",
    slices: "empty",
    ordinary_dispatch: "absent",
    test_execution: "absent",
    special_dispatch: "absent",
    amendment: "absent",
    repair: "absent",
    panels: "absent",
    heartbeat: "missing",
    process: "missing",
    launch_claim: "absent",
    run_lock: "acquired",
    launch_fence: "acquired-base-advance",
    git_identity: "registered-clean-attached",
    origin: "exact-stable",
    ancestry: "ancestor",
    crash_point: "old-eligible",
    ...overrides,
  };
}
